# here we are creating a single container in a pod
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample1
#spec:
#  containers:
#    - name: nginx
#      image: nginx

# here we are creating two container in a pod
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample2
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#    - name: mongodb
#      image: mongo

# in this we are creating a two container in a pod with command
# to exec to a container we use command kubectl exec -it sample3 -c centos -- bash
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample3
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#    - name: centos
#      image: centos:7
#      command: ["sleep", "1000000"]

# in this we one container with some resoures to give cpu 5000
#kind: Pod
#apiVersion: v1
#metadata:
#  name: sample4
#spec:
#  containers:
#    - name: nginx
#      image: nginx
#      resources:
#        requests:
#          cpu: 5000
#herewe are also crating one container with the env variable URL and with the value
kind: Pod
apiVersion:v1
metadata:
  name: sample5
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: URL
          value: example.com